---
title       : Dhruv K Pant Slidify Presentation
subtitle    : 
author      : Dhruv K Pant
job         : Bioinformatics Scientist
framework   : io2012        # {io2012, html5slides, shower, dzslides, ...}
highlighter : highlight.js  # {highlight.js, prettify, highlight}
hitheme     : tomorrow      # 
widgets     : []            # {mathjax, quiz, bootstrap}
mode        : selfcontained # {standalone, draft}
knit        : slidify::knit2slides
---

## Goal of the Analysis - 
To explore the 'IRIS' dataset and train a classifier(s) to predict the species of 
a plant when provided with certain attributes (eg. petal length ..)


---

Explore the IRIS dataset
This is a small dataset with `r nrow(iris)` rows and `r ncol(iris)` columns. 
The figure explores two parameters, petal length and sepal length 
for the 3 plant species. 

```{r echo=FALSE}
data(iris)
#summary(iris)
library(ggplot2)
p <- ggplot(iris,aes(Sepal.Length,Petal.Length)) + geom_point()
p <- p + facet_grid(. ~ Species)
p

```

---

The link below displays the Shiny App. Here, the user can input various parameters (petal length ,..) and a choice of 
classifiers (Random Forest, Naive Bayes) to predict which type of plant corresponds to the chosen parameters. 


http://dhruv-github.shinyapps.io/dkp_shiny_app/

---

Conclusions -
Two classifiers (**Random Forests** and **Naive Bayes**) have been developed and deployed over a Shiny App to enable web based prediction 
of plant species.  One finds that the two classifiers do not always agree in their predictions.   

Additional work could include adding more 
classifiers (as drop down options) and some measure of the accuracy of the classifiers.

---




